.TH walng 1
.SH NAME
walng \- color template generator for base16 framework

.SH SYNOPSIS
.B walng
[options]

.SH OPTIONS
.TP
.B \-\-config
path to config file
.TP
.B \-\-theme
path or url to theme file
.TP
.B \-\-help
prints the help and exit
.TP
.B \-\-version
prints the version and exit

.SH CONFIGURATION
walng uses one configuration file and its required
.IP 1. 4
The config file which defaults to $XDG_CONFIG_HOME/walng/config.yaml
